# Generated by Django 2.0.7 on 2018-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180717_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='type',
            field=models.SmallIntegerField(default='1', verbose_name='类型'),
        ),
    ]
