# Generated by Django 2.0.7 on 2018-07-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_picture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='type',
            field=models.SmallIntegerField(choices=[('1', '轮播图'), (2, '广告图')], default=1, verbose_name='类型'),
        ),
    ]
