# Generated by Django 2.0.7 on 2018-07-18 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180717_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='售价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='市场价')),
                ('picture', models.ImageField(upload_to='product/%Y%m%d', verbose_name='主图')),
                ('detail', models.TextField(max_length=3000, verbose_name='详情')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Category')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.AlterField(
            model_name='picture',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '轮播图'), (2, '广告图')], default=1, verbose_name='类型'),
        ),
    ]
