# Generated by Django 2.0.7 on 2018-07-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180719_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcartproduct',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
