# Generated by Django 2.0.7 on 2018-07-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_uuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=30, verbose_name='产品类型')),
                ('yuanliao_chandi', models.CharField(max_length=15, verbose_name='原料产地')),
                ('product_chandi', models.CharField(max_length=10, verbose_name='产地')),
                ('peiliao', models.CharField(max_length=50, verbose_name='配料')),
                ('baozhiqi', models.CharField(max_length=18, verbose_name='保质期')),
                ('savemethod', models.CharField(max_length=20, verbose_name='保存方法')),
                ('eatmethod', models.CharField(max_length=20, verbose_name='实用方法')),
                ('picture', models.ImageField(upload_to='product/%Y%m%d', verbose_name='配图')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '详情',
                'verbose_name_plural': '详情',
            },
        ),
    ]
